# Installing and Using Pandas

In [1]:
import pandas as pd
import numpy as np
print('Pandas version:',pd.__version__ )
print('NumPy version:',np.__version__ )

Pandas version: 2.2.2
NumPy version: 1.26.4


# Introducing Panda Objects

## Pandas Series Objects

In [2]:
data = pd.Series([2.5, 3.14, 'Tacos', 7])

print(data)

0      2.5
1     3.14
2    Tacos
3        7
dtype: object


### Series as NumPy array

In [3]:
data = pd.Series([0, 2.5, 5, 7.5, 10],
                 index=['1.', '2.', '3.', '4.', '5.'])

print('The whole series:\n', data)
print('\nThe specified series:', data['3.'])

The whole series:
 1.     0.0
2.     2.5
3.     5.0
4.     7.5
5.    10.0
dtype: float64

The specified series: 5.0


### Series as specialized dictionary

In [4]:
homeruns_dict = {'Barry Bonds': 762,
                'Hank Aaron': 755,
                'Babe Ruth': 714,
                'Albert Pujols': 703,
                'Alex Rodriguez': 696,
                'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630,
                'Jim Thome' : 612,
                'Sammy Sosa' : 609,
                'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)
print('Top three homerun hitters:\n',homeruns['Barry Bonds': 'Babe Ruth'])

Top three homerun hitters:
 Barry Bonds    762
Hank Aaron     755
Babe Ruth      714
dtype: int64


### Constructing series objects

In [5]:
P = pd.Series({'x': 100, 'y': 200, 'z': 300}, index=['z', 'y'])
print('The desired index is:\n',P)

The desired index is:
 z    300
y    200
dtype: int64


## The Pandas DataFrame Object

### DataFrame as NumPy array

In [6]:
hits_dict = {'Barry Bonds': 2935,
                'Hank Aaron': 3771,
                'Babe Ruth': 2873,
                'Albert Pujols': 3384,
                'Alex Rodriguez': 3115,
                'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781,
                'Jim Thome' : 2328,
                'Sammy Sosa' : 2408,
                'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
players

The best baseball players are:


Homeruns  Hits
Barry Bonds           762  2935
Hank Aaron            755  3771
Babe Ruth             714  2873
Albert Pujols         703  3384
Alex Rodriguez        696  3115
Willie Mays           660  3283
Ken Griffey Jr.       630  2781
Jim Thome             612  2328
Sammy Sosa            609  2408
Frank Robinson        586  2943

### Constructing DataFrame objects

In [7]:
pd.DataFrame([{'a': 3, 'b': 2, 'c':1}, {'a':4,'b': 5, 'c': 6}],
             columns=['a', 'b', 'c'],
             index=['Row 1', 'Row 2'])

a  b  c
Row 1  3  2  1
Row 2  4  5  6

## Pandas index object

### Index as immutable array

In [8]:
i = pd.Index([6, 3.0, 9.4, 'tacos', 7])
print('The index from the third value on:\n',i[2:])

The index from the third value on:
 Index([9.4, 'tacos', 7], dtype='object')


In [9]:
# The array can't be changed
i[2] = 99

TypeError: Index does not support mutable operations

### Index as ordered set

In [ ]:
I1 = pd.Index([7, 5, 4, 3, 6])
I2 = pd.Index([1, 5, 4, 3, 2])

print('Union of the indexes:',I1.union(I2))
print('Intersection of the indexes:',I1.intersection(I2))
print('Diffferences of the indexes:',I1.symmetric_difference(I2))

Union of the indexes: Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')
Intersection of the indexes: Index([5, 4, 3], dtype='int64')
Diffferences of the indexes: Index([1, 2, 6, 7], dtype='int64')


# Data Indexing and Selection

## Data Selection in series

### Series as dictionary

In [ ]:
players = pd.DataFrame({'Homeruns': homeruns,
                        'Hits': hits})
print('The best baseball players are:')
print('Here are the hits for all the players:\n',players['Hits'])


The best baseball players are:
Here are the hits for all the players:
 Barry Bonds        2935
Hank Aaron         3771
Babe Ruth          2873
Albert Pujols      3384
Alex Rodriguez     3115
Willie Mays        3283
Ken Griffey Jr.    2781
Jim Thome          2328
Sammy Sosa         2408
Frank Robinson     2943
Name: Hits, dtype: int64


### Series as 1D array

In [ ]:
print('Players that have 3000 hits and 700 homeruns:')
players[(homeruns > 700) & (hits > 2800)]

Players that have 3000 hits and 700 homeruns:


Homeruns  Hits
Barry Bonds         762  2935
Hank Aaron          755  3771
Babe Ruth           714  2873
Albert Pujols       703  3384

### Indexers: loc, iloc and ix

In [ ]:
data = pd.Series(['Hank Aaron    ', 'Albert Pujols', 'Barry Bonds  ']
                 , index=[1, 2, 3])
print('The top three players in baseball:\n', data)

print('Here\n',data.iloc[0])

The top three players in baseball:
 1    Hank Aaron    
2     Albert Pujols
3     Barry Bonds  
dtype: object
Here
 1    Hank Aaron    
2     Albert Pujols
dtype: object


In [ ]:
AB_dict = {'Barry Bonds': 9847, 'Hank Aaron': 12364,
                'Babe Ruth': 8399, 'Albert Pujols': 11421,
                'Alex Rodriguez': 10566, 'Willie Mays' : 10881,
                'Ken Griffey Jr.' : 9801, 'Jim Thome' : 8422,
                'Sammy Sosa' : 8813, 'Frank Robinson' : 10006
            }
AB = pd.Series(AB_dict)

hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

players = pd.DataFrame({'Hits': hits,
                        'AB': AB})
print('The best baseball players are:')
players['BAA'] = players['Hits'] / players['AB']
players.T

The best baseball players are:


Barry Bonds    Hank Aaron    Babe Ruth  Albert Pujols  Alex Rodriguez  \
Hits   2935.00000   3771.000000  2873.000000    3384.000000     3115.000000   
AB     9847.00000  12364.000000  8399.000000   11421.000000    10566.000000   
BAA       0.29806      0.304998     0.342065       0.296296        0.294814   

       Willie Mays  Ken Griffey Jr.    Jim Thome   Sammy Sosa  Frank Robinson  
Hits   3283.000000      2781.000000  2328.000000  2408.000000     2943.000000  
AB    10881.000000      9801.000000  8422.000000  8813.000000    10006.000000  
BAA       0.301719         0.283747     0.276419     0.273233        0.294124

### Additional Indexing conventions

In [ ]:
players[players.BAA > .300]

Hits     AB       BAA
Hank Aaron   3771  12364  0.304998
Babe Ruth    2873   8399  0.342065
Willie Mays  3283  10881  0.301719

# Operating on Data in Pandas


## Ufuncs: Index Preservation

In [ ]:
r = np.random.RandomState(99)
array = pd.DataFrame(r.randint(0, 20, (5, 5)),
        columns=['A', 'B', 'C', 'D', 'E'])
print('Here is the e^r 5x5 array:')
np.exp(array)

Here is the e^r 5x5 array:


A             B             C            D             E
0  2.718282e+00  2.008554e+01  2.980958e+03  8103.083928  2.980958e+03
1  6.565997e+07  5.459815e+01  1.484132e+02     2.718282  2.008554e+01
2  2.415495e+07  2.718282e+00  8.886111e+06   403.428793  5.987414e+04
3  7.389056e+00  1.000000e+00  1.627548e+05  2980.957987  2.980958e+03
4  1.096633e+03  3.269017e+06  3.269017e+06   148.413159  1.202604e+06

### Ufuncs: Index Alignment

In [ ]:
homeruns_dict = {'Barry Bonds': 762, 'Hank Aaron': 755,
                'Babe Ruth': 714, 'Albert Pujols': 703,
                'Alex Rodriguez': 696, 'Willie Mays' : 660,
                'Ken Griffey Jr.' : 630, 'Jim Thome' : 612,
                'Sammy Sosa' : 609, 'Frank Robinson' : 586
                }
homeruns = pd.Series(homeruns_dict)

hits_dict = {'Pete Rose': 4256, 'Hank Aaron': 3771,
                'Ty Cobb': 4189, 'Albert Pujols': 3384,
                'Stan Musial': 3630, 'Tris Speaker' : 3514,
                'Honus Wagner' : 3430, 'Derek Jeter' : 3465,
                'Willie Mays' : 3283, 'Paul Molitor' : 3319
                }
hits = pd.Series(hits_dict)

homeruns.index | hits.index

/tmp/ipykernel_9764/4277536936.py:17: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead.
  homeruns.index | hits.index


Index(['Albert Pujols', 'Alex Rodriguez', 'Babe Ruth', 'Barry Bonds',
       'Derek Jeter', 'Frank Robinson', 'Hank Aaron', 'Honus Wagner',
       'Jim Thome', 'Ken Griffey Jr.', 'Paul Molitor', 'Pete Rose',
       'Sammy Sosa', 'Stan Musial', 'Tris Speaker', 'Ty Cobb', 'Willie Mays'],
      dtype='object')

In [ ]:
hits_dict = {'Barry Bonds': 2935, 'Hank Aaron': 3771,
                'Babe Ruth': 2873, 'Albert Pujols': 3384,
                'Alex Rodriguez': 3115, 'Willie Mays' : 3283,
                'Ken Griffey Jr.' : 2781, 'Jim Thome' : 2328,
                'Sammy Sosa' : 2408, 'Frank Robinson' : 2943
                }
hits = pd.Series(hits_dict)

print('The rate of hits before a homerun:\n',hits / homeruns)

The rate of hits before a homerun:
 Barry Bonds        3.851706
Hank Aaron         4.994702
Babe Ruth          4.023810
Albert Pujols      4.813656
Alex Rodriguez     4.475575
Willie Mays        4.974242
Ken Griffey Jr.    4.414286
Jim Thome          3.803922
Sammy Sosa         3.954023
Frank Robinson     5.022184
dtype: float64


In [ ]:
print('How many hits were not homeruns:\n',hits.subtract(homeruns, fill_value=0))

How many hits were not homeruns:
 Barry Bonds        2173
Hank Aaron         3016
Babe Ruth          2159
Albert Pujols      2681
Alex Rodriguez     2419
Willie Mays        2623
Ken Griffey Jr.    2151
Jim Thome          1716
Sammy Sosa         1799
Frank Robinson     2357
dtype: int64


## Ufuncs: Operations Between DataFrame and Series

In [ ]:
N = r.randint(20, size=(5, 5))
print('The orignal 5x5 array:\n', N)
print('The 5x5 array minus first value:\n', N - N[0,0])

M = pd.DataFrame(N, columns=list('ABCDE'))
M.subtract(M['C'], axis=0)


The orignal 5x5 array:
 [[ 3 11  6  7  9]
 [ 2  7  5  1 16]
 [ 2  7  0  6 18]
 [ 8  4 18 13 15]
 [ 0  1 16 11  3]]
The 5x5 array minus first value:
 [[ 0  8  3  4  6]
 [-1  4  2 -2 13]
 [-1  4 -3  3 15]
 [ 5  1 15 10 12]
 [-3 -2 13  8  0]]


A   B  C  D   E
0  -3   5  0  1   3
1  -3   2  0 -4  11
2   2   7  0  6  18
3 -10 -14  0 -5  -3
4 -16 -15  0 -5 -13

# Handling Missing Data

## Missing Data in Pandas

### Pythonic missing data

In [ ]:
X1 = np.array([7, 3.14, 4 + 3j, 8])
print('The sum of the first array:',X1.sum())

X2 = np.array([7, 3.14, 4 + 3j, None])
print('The sum of the second array:',X2.sum())

The sum of the first array: (22.14+3j)


TypeError: unsupported operand type(s) for +: 'complex' and 'NoneType'

### Missing numerical data

In [ ]:
Y = np.array([7, np.nan, 3.14, 4+ 3j]) 
print('Result of calculations including nan:\n',Y.sum(), Y.min(), Y.max())
print('Result of calculations excluding nan:\n',np.nansum(Y), np.nanmin(Y), np.nanmax(Y))


Result of calculations including nan:
 (nan+3j) (nan+0j) (nan+0j)
Result of calculations excluding nan:
 (14.14+3j) (3.14+0j) (7+0j)


### NaN and None in Pandas

In [ ]:
pd.Series([7, np.nan, 3.14, None])

0    7.00
1     NaN
2    3.14
3     NaN
dtype: float64

## Operating on null values

### Detecting null values

In [ ]:
data = pd.Series([7, np.nan, 'tacos', None])
print('The value types in the series:\n',data[data.notnull()])
print('\nThe null types in the series:\n',data[data.isnull()])


The value types in the series:
 0        7
2    tacos
dtype: object

The null types in the series:
 1     NaN
3    None
dtype: object


### Dropping null values

In [ ]:
data = pd.DataFrame([[3,      np.nan, 4],
                   [7,      8,     3.14],
                   [np.nan, 1,      0]])
print('Array with null backfilled:\n',data.fillna(method='bfill'))
print('\nArray with null frontfilled:\n',data.fillna(method='ffill'))


Array with null backfilled:
      0    1     2
0  3.0  8.0  4.00
1  7.0  8.0  3.14
2  NaN  1.0  0.00

Array with null frontfilled:
      0    1     2
0  3.0  NaN  4.00
1  7.0  8.0  3.14
2  7.0  1.0  0.00


# Hierarchical Indexing

## A Multiply indexed series

### Pandas MultiIndex

In [ ]:
Teams = [('LA Dodgers', 2020), ('Houston Astros', 2017),
         ('Washington Nationals', 2019), ('Boston RedSox', 2018),
         ('LA Dodgers', 2018), ('Houston Astros', 2019),
         ('LA Dodgers', 2017), ('Tampa Bay Rays', 2020)]
Wins = [43, 101,
       93, 108,
       92, 107,
       104, 40]
Winner = pd.Series(Wins, index=Teams)
#Winner = Winner.reindex(Teams)
Winner


(LA Dodgers, 2020)               43
(Houston Astros, 2017)          101
(Washington Nationals, 2019)     93
(Boston RedSox, 2018)           108
(LA Dodgers, 2018)               92
(Houston Astros, 2019)          107
(LA Dodgers, 2017)              104
(Tampa Bay Rays, 2020)           40
dtype: int64

In [ ]:
Winner_df = Winner.unstack()
Winner_df

ValueError: index must be a MultiIndex to unstack, <class 'pandas.core.indexes.base.Index'> was passed

## Methods of MultiIndex creation

In [ ]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.216691  0.996926
  2  0.772459  0.855296
b 1  0.464916  0.290822
  2  0.544669  0.460006

# Combining Datasets: Concat and Append

In [ ]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

## Recall: Concatenation of NumPy Arrays

In [ ]:
x = [[1, 2],[3, 4]]
y = [[5, 6],[7, 8]]
np.concatenate([x, y], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Simple Concatenation with pd.concat

In [ ]:
s1 = pd.Series(['Barry Bonds', 'Hank Aaron', 'Albert Pujols'], index=[1, 2, 3])
s2 = pd.Series(['Derek Jeter', 'Pete Rose', 'Willie Mays'], index=[4, 5, 6])
pd.concat([s1, s2])

1      Barry Bonds
2       Hank Aaron
3    Albert Pujols
4      Derek Jeter
5        Pete Rose
6      Willie Mays
dtype: object

### Duplicate Indices

In [ ]:
x = make_df('AB', [1, 2])
y = make_df('AB', [3, 4])
y.index = x.index  # make duplicate indices!
display(x, y, pd.concat([x, y]))

A   B
1  A1  B1
2  A2  B2

A   B
1  A3  B3
2  A4  B4

A   B
1  A1  B1
2  A2  B2
1  A3  B3
2  A4  B4

#### Catching the repeats as an error

In [ ]:
try:
    pd.concat([x, y], verify_integrity=True)
except ValueError as e:
    print("ValueError:", e)

ValueError: Indexes have overlapping values: Index([1, 2], dtype='int64')


#### Ignoring the index

In [ ]:
display(x, y, pd.concat([x, y], ignore_index=True))

A   B
1  A1  B1
2  A2  B2

A   B
1  A3  B3
2  A4  B4

A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

#### Adding MultiIndex Keys

In [ ]:
display(x, y, pd.concat([x, y], keys=['x', 'y']))

A   B
1  A1  B1
2  A2  B2

A   B
1  A3  B3
2  A4  B4

A   B
x 1  A1  B1
  2  A2  B2
y 1  A3  B3
  2  A4  B4

### Concatenation with joins

In [ ]:
X1 = make_df('ABC', [1, 2, 3])
X2 = make_df('BCD', [4, 5, 6])
display(X1, X2, pd.concat([X1, X2]))

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

B   C   D
4  B4  C4  D4
5  B5  C5  D5
6  B6  C6  D6

A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3   A3  B3  C3  NaN
4  NaN  B4  C4   D4
5  NaN  B5  C5   D5
6  NaN  B6  C6   D6

In [ ]:
display(X1, X2, pd.concat([X1, X2], join='inner'))

A   B   C
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

B   C   D
4  B4  C4  D4
5  B5  C5  D5
6  B6  C6  D6

B   C
1  B1  C1
2  B2  C2
3  B3  C3
4  B4  C4
5  B5  C5
6  B6  C6

# Combining Datasets: Merge and Join

## Categories of joins

### One to one joins

In [ ]:
X1 = pd.DataFrame({'Employee': ['Colin', 'John', 'Trish', 'Cameron'],
                    'Group': ['Tester', 'Engineer', 'Coder', 'Programmer']})
X2 = pd.DataFrame({'Employee': ['Colin', 'John', 'Trish', 'Cameron'],
                    'Hire date': [2023, 2022, 2021, 2009]})
display(X1, X2)

Employee       Group
0    Colin      Tester
1     John    Engineer
2    Trish       Coder
3  Cameron  Programmer

Employee  Hire date
0    Colin       2023
1     John       2022
2    Trish       2021
3  Cameron       2009

In [ ]:
X3 = pd.merge(X1, X2)
X3

Employee       Group  Hire date
0    Colin      Tester       2023
1     John    Engineer       2022
2    Trish       Coder       2021
3  Cameron  Programmer       2009

### Many to one joins

In [ ]:
X4 = pd.DataFrame({'Group': ['Tester', 'Engineer', 'Coder', 'Programmer'],
                    'Supervisor': ['Imad', 'Darrell', 'Aaron', 'Kalpesh']})
display(X4, pd.merge(X3, X4))

Group Supervisor
0      Tester       Imad
1    Engineer    Darrell
2       Coder      Aaron
3  Programmer    Kalpesh

Employee       Group  Hire date Supervisor
0    Colin      Tester       2023       Imad
1     John    Engineer       2022    Darrell
2    Trish       Coder       2021      Aaron
3  Cameron  Programmer       2009    Kalpesh

### Many to many joins

In [ ]:
X5 = pd.DataFrame({'Group': ['Tester', 'Engineer', 'Coder', 'Programmer'],
                    'Skills': ['Soldering', 'Analysis', 'Python', 'C++',]})
display(X5, pd.merge(X1, X5))

Group     Skills
0      Tester  Soldering
1    Engineer   Analysis
2       Coder     Python
3  Programmer        C++

Employee       Group     Skills
0    Colin      Tester  Soldering
1     John    Engineer   Analysis
2    Trish       Coder     Python
3  Cameron  Programmer        C++

## Specification of the merge key

### The on keyword

In [ ]:
display(pd.merge(X1, X2, on='Employee'))

Employee       Group  Hire date
0    Colin      Tester       2023
1     John    Engineer       2022
2    Trish       Coder       2021
3  Cameron  Programmer       2009

### The left_index and right_index keywords

In [ ]:
X1a = X1.set_index('Employee')
X2a = X2.set_index('Employee')
display(pd.merge(X1a, X2a, left_index=True, right_index=True))

Group  Hire date
Employee                       
Colin         Tester       2023
John        Engineer       2022
Trish          Coder       2021
Cameron   Programmer       2009

In [ ]:
display(X1a.join(X2a))

Group  Hire date
Employee                       
Colin         Tester       2023
John        Engineer       2022
Trish          Coder       2021
Cameron   Programmer       2009

## Specifying set arithmetic for joins

In [ ]:
X6 = pd.DataFrame({'Name': ['Wesley', 'Colin', 'Zach'],
                    'Food': ['Watermelon', 'Chicken', 'Pizza']},
                   columns=['Name', 'Food'])
X7 = pd.DataFrame({'Name': ['Zach', 'Corbin'],
                    'Drink': ['Tea', 'Water']},
                   columns=['Name', 'Drink'])
display(X6, X7, pd.merge(X6, X7))

Name        Food
0  Wesley  Watermelon
1   Colin     Chicken
2    Zach       Pizza

Name  Drink
0    Zach    Tea
1  Corbin  Water

Name   Food Drink
0  Zach  Pizza   Tea

In [ ]:
pd.merge(X6, X7, how='inner')

Name   Food Drink
0  Zach  Pizza   Tea

In [ ]:
display(X6, X7, pd.merge(X6, X7, how='outer'))

Name        Food
0  Wesley  Watermelon
1   Colin     Chicken
2    Zach       Pizza

Name  Drink
0    Zach    Tea
1  Corbin  Water

Name        Food  Drink
0   Colin     Chicken    NaN
1  Corbin         NaN  Water
2  Wesley  Watermelon    NaN
3    Zach       Pizza    Tea

In [ ]:
display(X6, X7, pd.merge(X6, X7, how='left'))

Name        Food
0  Wesley  Watermelon
1   Colin     Chicken
2    Zach       Pizza

Name  Drink
0    Zach    Tea
1  Corbin  Water

Name        Food Drink
0  Wesley  Watermelon   NaN
1   Colin     Chicken   NaN
2    Zach       Pizza   Tea

## Overlapping Columns Names: The suffixes keyword

In [ ]:
X8 = pd.DataFrame({'Name': ['Zach', 'JW', 'Colin', 'Michael'],
                    'Rank': [4, 2, 3, 1]})
X9 = pd.DataFrame({'Name': ['Zach', 'JW', 'Colin', 'Michael'],
                    'Rank': [3, 4, 2, 1]})
display(X8, X9, pd.merge(X8, X9, on="Name"))

Name  Rank
0     Zach     4
1       JW     2
2    Colin     3
3  Michael     1

Name  Rank
0     Zach     3
1       JW     4
2    Colin     2
3  Michael     1

Name  Rank_x  Rank_y
0     Zach       4       3
1       JW       2       4
2    Colin       3       2
3  Michael       1       1

In [ ]:
display(X8, X9, pd.merge(X8, X9, on="Name", suffixes=["_L", "_R"]))

Name  Rank
0     Zach     4
1       JW     2
2    Colin     3
3  Michael     1

Name  Rank
0     Zach     3
1       JW     4
2    Colin     2
3  Michael     1

Name  Rank_L  Rank_R
0     Zach       4       3
1       JW       2       4
2    Colin       3       2
3  Michael       1       1

# Aggregation and Grouping

## Planets Data

In [ ]:
import seaborn as sns
planets = sns.load_dataset('planets')
planets.shape

(1035, 6)

In [ ]:
planets.head()

method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

## Simple Aggregation in Pandas

In [ ]:
r = np.random.RandomState(99)
s = pd.Series(r.rand(10))
print('The series of random numbers is:\n',s)
print('The sum of the series is:',s.sum())
print('The mean of the series is:',s.mean())

The series of random numbers is:
 0    0.672279
1    0.488078
2    0.825495
3    0.031446
4    0.808050
5    0.565617
6    0.297622
7    0.046696
8    0.990627
9    0.006826
dtype: float64
The sum of the series is: 4.732737254234297
The mean of the series is: 0.4732737254234297


In [ ]:
df = pd.DataFrame({'A': r.rand(5),
                   'B': r.rand(5)})
print('The series of 10 random numbers:\n', df)
print('\nThe mean of A and B:\n',df.mean())
print('\nThe mean across each row:\n',df.mean(axis='columns'))

The series of 10 random numbers:
           A         B
0  0.546269  0.105540
1  0.516253  0.613880
2  0.720418  0.243656
3  0.822525  0.826946
4  0.235267  0.465529

The mean of A and B:
 A    0.568146
B    0.451110
dtype: float64

The mean across each row:
 0    0.325904
1    0.565066
2    0.482037
3    0.824736
4    0.350398
dtype: float64


In [ ]:
planets.dropna().describe()

number  orbital_period        mass    distance         year
count  498.00000      498.000000  498.000000  498.000000   498.000000
mean     1.73494      835.778671    2.509320   52.068213  2007.377510
std      1.17572     1469.128259    3.636274   46.596041     4.167284
min      1.00000        1.328300    0.003600    1.350000  1989.000000
25%      1.00000       38.272250    0.212500   24.497500  2005.000000
50%      1.00000      357.000000    1.245000   39.940000  2009.000000
75%      2.00000      999.600000    2.867500   59.332500  2011.000000
max      6.00000    17337.500000   25.000000  354.000000  2014.000000

## GroupBy: Split, Apply, Combine

### Split, Apply, Combine

In [ ]:
df = pd.DataFrame({'Key': ['A', 'B', 'C', 'D', 'E', 'E', 'C', 'D', 'A', 'B'],
                   'Data': range(10)}, columns=['Key', 'Data'])
df

Key  Data
0   A     0
1   B     1
2   C     2
3   D     3
4   E     4
5   E     5
6   C     6
7   D     7
8   A     8
9   B     9

In [ ]:
df.groupby('Key')

In [ ]:
df.groupby('Key').sum()

Data
Key      
A       8
B      10
C       8
D      10
E       9

### The GroupBy object

#### Column indexing

In [ ]:
planets.groupby('method')['orbital_period']

In [ ]:
planets.groupby('method')['orbital_period'].median()

method
Astrometry                         631.180000
Eclipse Timing Variations         4343.500000
Imaging                          27500.000000
Microlensing                      3300.000000
Orbital Brightness Modulation        0.342887
Pulsar Timing                       66.541900
Pulsation Timing Variations       1170.000000
Radial Velocity                    360.200000
Transit                              5.714932
Transit Timing Variations           57.011000
Name: orbital_period, dtype: float64

#### Iteration over groups

In [ ]:
for (method, group) in planets.groupby('method'):
    print("{0:30s} shape={1}".format(method, group.shape))

Astrometry                     shape=(2, 6)
Eclipse Timing Variations      shape=(9, 6)
Imaging                        shape=(38, 6)
Microlensing                   shape=(23, 6)
Orbital Brightness Modulation  shape=(3, 6)
Pulsar Timing                  shape=(5, 6)
Pulsation Timing Variations    shape=(1, 6)
Radial Velocity                shape=(553, 6)
Transit                        shape=(397, 6)
Transit Timing Variations      shape=(4, 6)


#### Dispatch methods

In [ ]:
planets.groupby('method')['year'].describe()

count         mean       std     min      25%  \
method                                                                         
Astrometry                       2.0  2011.500000  2.121320  2010.0  2010.75   
Eclipse Timing Variations        9.0  2010.000000  1.414214  2008.0  2009.00   
Imaging                         38.0  2009.131579  2.781901  2004.0  2008.00   
Microlensing                    23.0  2009.782609  2.859697  2004.0  2008.00   
Orbital Brightness Modulation    3.0  2011.666667  1.154701  2011.0  2011.00   
Pulsar Timing                    5.0  1998.400000  8.384510  1992.0  1992.00   
Pulsation Timing Variations      1.0  2007.000000       NaN  2007.0  2007.00   
Radial Velocity                553.0  2007.518987  4.249052  1989.0  2005.00   
Transit                        397.0  2011.236776  2.077867  2002.0  2010.00   
Transit Timing Variations        4.0  2012.500000  1.290994  2011.0  2011.75   

                                  50%      75%     max  
method                                                  
Astrometry                     2011.5  2012.25  2013.0  
Eclipse Timing Variations      2010.0  2011.00  2012.0  
Imaging                        2009.0  2011.00  2013.0  
Microlensing                   2010.0  2012.00  2013.0  
Orbital Brightness Modulation  2011.0  2012.00  2013.0  
Pulsar Timing                  1994.0  2003.00  2011.0  
Pulsation Timing Variations    2007.0  2007.00  2007.0  
Radial Velocity                2009.0  2011.00  2014.0  
Transit                        2012.0  2013.00  2014.0  
Transit Timing Variations      2012.5  2013.25  2014.0

### Aggregate, filter, transform, apply

In [ ]:
rng = np.random.RandomState(99)
df = pd.DataFrame({'Key': ['A', 'B', 'C', 'D', 'E', 'E', 'D', 'C', 'B', 'A'],
                   'Data1': range(0, 20, 2),
                   'Data2': rng.randint(10, 20, 10)},
                   columns = ['Key', 'Data1', 'Data2'])
df

Key  Data1  Data2
0   A      0     11
1   B      2     13
2   C      4     19
3   D      6     18
4   E      8     19
5   E     10     18
6   D     12     12
7   C     14     14
8   B     16     15
9   A     18     14

#### Aggregation

In [ ]:
df.groupby('Key').aggregate(['min', 'median', 'max'])

Data1            Data2           
      min median max   min median max
Key                                  
A       0    9.0  18    11   12.5  14
B       2    9.0  16    13   14.0  15
C       4    9.0  14    14   16.5  19
D       6    9.0  12    12   15.0  18
E       8    9.0  10    18   18.5  19

In [ ]:
df.groupby('Key').aggregate({'Data1': 'min',
                             'Data2': 'max'})

Data1  Data2
Key              
A        0     14
B        2     15
C        4     19
D        6     18
E        8     19

#### Filtering

In [ ]:
def filter_func(x):
    return x['Data2'].std() > 3

display(df, df.groupby('Key').std(), df.groupby('Key').filter(filter_func))

Key  Data1  Data2
0   A      0     11
1   B      2     13
2   C      4     19
3   D      6     18
4   E      8     19
5   E     10     18
6   D     12     12
7   C     14     14
8   B     16     15
9   A     18     14

Data1     Data2
Key                     
A    12.727922  2.121320
B     9.899495  1.414214
C     7.071068  3.535534
D     4.242641  4.242641
E     1.414214  0.707107

Key  Data1  Data2
2   C      4     19
3   D      6     18
6   D     12     12
7   C     14     14

#### Transformation

In [ ]:
df.groupby('Key').transform(lambda x: x - x.mean())

Data1  Data2
0   -9.0   -1.5
1   -7.0   -1.0
2   -5.0    2.5
3   -3.0    3.0
4   -1.0    0.5
5    1.0   -0.5
6    3.0   -3.0
7    5.0   -2.5
8    7.0    1.0
9    9.0    1.5

#### The apply() method

In [ ]:
def norm_by_data2(x):
    # x is a DataFrame of group values
    x['Data1'] /= x['Data2'].sum()
    return x

display(df, df.groupby('Key').apply(norm_by_data2))

C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\3883942059.py:6: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  display(df, df.groupby('Key').apply(norm_by_data2))


Key  Data1  Data2
0   A      0     11
1   B      2     13
2   C      4     19
3   D      6     18
4   E      8     19
5   E     10     18
6   D     12     12
7   C     14     14
8   B     16     15
9   A     18     14

Key     Data1  Data2
Key                       
A   0   A  0.000000     11
    9   A  0.720000     14
B   1   B  0.071429     13
    8   B  0.571429     15
C   2   C  0.121212     19
    7   C  0.424242     14
D   3   D  0.200000     18
    6   D  0.400000     12
E   4   E  0.216216     19
    5   E  0.270270     18

### Specifying the split key

In [ ]:
display(df, df.groupby(df['Key']).sum())

Key  Data1  Data2
0   A      0     11
1   B      2     13
2   C      4     19
3   D      6     18
4   E      8     19
5   E     10     18
6   D     12     12
7   C     14     14
8   B     16     15
9   A     18     14

Data1  Data2
Key              
A       18     25
B       18     28
C       18     33
D       18     30
E       18     37

#### A dictionary or series mapping index to group

In [ ]:
df2 = df.set_index('Key')
mapping = {'A': 'vowel', 'B': 'consonant', 'C': 'consonant', 'D': 'consonant', 'E': 'vowel',}
display(df2.groupby(mapping).sum())

Data1  Data2
Key                    
consonant     54     91
vowel         36     62

#### Any Python Function

In [ ]:
display(df2.groupby(str.lower).mean())

Data1  Data2
Key              
a      9.0   12.5
b      9.0   14.0
c      9.0   16.5
d      9.0   15.0
e      9.0   18.5

#### A list of valid keys

In [ ]:
df2.groupby([str.lower, mapping]).mean()

Data1  Data2
Key Key                    
a   vowel        9.0   12.5
b   consonant    9.0   14.0
c   consonant    9.0   16.5
d   consonant    9.0   15.0
e   vowel        9.0   18.5

# Pivot Tables

## Motivating Pivot Tables

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

## Pivot Tables by Hand

In [ ]:
titanic.groupby(['sex', 'class'])['age'].aggregate('mean').unstack()

C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\412720707.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  titanic.groupby(['sex', 'class'])['age'].aggregate('mean').unstack()


class       First     Second      Third
sex                                    
female  34.611765  28.722973  21.750000
male    41.281386  30.740707  26.507589

## Pivot Table Syntax

In [ ]:
titanic.pivot_table('age', index='sex', columns='class')

C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\3304118054.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('age', index='sex', columns='class')


class       First     Second      Third
sex                                    
female  34.611765  28.722973  21.750000
male    41.281386  30.740707  26.507589

### Multi level pivot tables

In [ ]:
age = pd.cut(titanic['age'], [10, 45, 80])
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])


C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\1245285829.py:3: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('survived', ['sex', age], [fare, 'class'])


fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (10, 45]              NaN  0.920000  0.509804          0.984375   
       (45, 80]              NaN  0.666667  1.000000          0.950000   
male   (10, 45]              0.0  0.090909  0.138122          0.509434   
       (45, 80]              NaN  0.090909  0.000000          0.261905   

fare                                 
class              Second     Third  
sex    age                           
female (10, 45]  0.911765  0.346154  
       (45, 80]  1.000000  0.000000  
male   (10, 45]  0.033333  0.142857  
       (45, 80]  0.000000       NaN

### Additional pivot table options

In [ ]:
titanic.pivot_table(index='sex', columns='class',
                    aggfunc={'survived':'sum', 'age':'mean'})

C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\561544949.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table(index='sex', columns='class',


age                       survived             
class       First     Second      Third    First Second Third
sex                                                          
female  34.611765  28.722973  21.750000       91     70    72
male    41.281386  30.740707  26.507589       45     17    47

In [ ]:
titanic.pivot_table('age', index='sex', columns='class', margins=True)

C:\Users\Zachary.Cone.SERN\AppData\Local\Temp\ipykernel_23240\2435163161.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  titanic.pivot_table('age', index='sex', columns='class', margins=True)


class       First     Second      Third        All
sex                                               
female  34.611765  28.722973  21.750000  27.915709
male    41.281386  30.740707  26.507589  30.726645
All     38.233441  29.877630  25.140620  29.699118

# Vectorized String Operations

## Introducing Pandas String Operations

In [ ]:
data = ['colin', 'Zach', 'WESLEY', 'CoRBiN']
names = pd.Series(data)
names.str.capitalize()

0     Colin
1      Zach
2    Wesley
3    Corbin
dtype: object

## Tables of Pandas String Methods

### Method similar to Python string methods

In [47]:
anime = pd.Series(['Naruto Uzimaki', 'Monkey D. Luffy', 'Ichigo Kurosaki',
                   'Tanjiro Kamado', 'Gojo Satoru', 'Son Goku'])

print('Anime series with cases swapped:\n',anime.str.swapcase())
print('\nAnime series all uppercased:\n',anime.str.upper())

Anime series with cases swapped:
 0     nARUTO uZIMAKI
1    mONKEY d. lUFFY
2    iCHIGO kUROSAKI
3     tANJIRO kAMADO
4        gOJO sATORU
5           sON gOKU
dtype: object

Anime series all uppercased:
 0     NARUTO UZIMAKI
1    MONKEY D. LUFFY
2    ICHIGO KUROSAKI
3     TANJIRO KAMADO
4        GOJO SATORU
5           SON GOKU
dtype: object


### Methods using regular methods

In [48]:
anime.str.extract('([A-Za-z]+)', expand=False)

0     Naruto
1     Monkey
2     Ichigo
3    Tanjiro
4       Gojo
5        Son
dtype: object

### Miscellaneous methods

In [49]:
anime.str.split().str.get(-1)

0     Uzimaki
1       Luffy
2    Kurosaki
3      Kamado
4      Satoru
5        Goku
dtype: object

#### Indicator variables

* A - Indicates they are children
 * B - Indicates they are an adult
 * C - Indicates they have superpowers
 * D - They use weapons

In [50]:
full_anime = pd.DataFrame({'name': anime,
                      'info': ['A|C|D', 'A|C', 'B|D',
                                    'A|D', 'B|C', 'B|C|D']})
full_anime

name   info
0   Naruto Uzimaki  A|C|D
1  Monkey D. Luffy    A|C
2  Ichigo Kurosaki    B|D
3   Tanjiro Kamado    A|D
4      Gojo Satoru    B|C
5         Son Goku  B|C|D

In [51]:
full_anime['info'].str.get_dummies('|')

A  B  C  D
0  1  0  1  1
1  1  0  1  0
2  0  1  0  1
3  1  0  0  1
4  0  1  1  0
5  0  1  1  1

# Working with Time Series

## Dates and Times in Python

### Native Python dates and times: datatime and dateutil

In [53]:
from datetime import datetime
datetime(year=2000, month=7, day=7)

datetime.datetime(2000, 7, 7, 0, 0)

In [54]:
from dateutil import parser
date = parser.parse("7th of July, 2000")
date

datetime.datetime(2000, 7, 7, 0, 0)

In [55]:
date.strftime('%A')

'Friday'

### Dates and times in pandas: best of both worlds

In [63]:
import pandas as pd
date = pd.to_datetime("7th of July, 2000")
date

Timestamp('2000-07-07 00:00:00')

In [64]:
date.strftime('%A')

'Friday'

## Pandas Time Series: Indexing by Time

In [72]:
index = pd.DatetimeIndex(['2000-07-07', '2000-08-08',
                          '2010-07-07', '2010-08-08'])
data = pd.Series([0, 1, 2, 3], index=index)
data['2000-07-07':'2010-07-07']

2000-07-07    0
2000-08-08    1
2010-07-07    2
dtype: int64

In [73]:
data['2010']

2010-07-07    2
2010-08-08    3
dtype: int64

## Pandas Time Series Data Structures

In [75]:
dates = pd.to_datetime([datetime(2000, 7, 4), '5th of July, 2000',
                       '2000-Jul-6', '07-07-2000', '20100708'])
dates.to_period('D')

PeriodIndex(['2000-07-04', '2000-07-05', '2000-07-06', '2000-07-07',
             '2010-07-08'],
            dtype='period[D]')

### Regular sequences: pd.date_range()

In [76]:
pd.date_range('2000-07-07', periods=10, freq='D')

DatetimeIndex(['2000-07-07', '2000-07-08', '2000-07-09', '2000-07-10',
               '2000-07-11', '2000-07-12', '2000-07-13', '2000-07-14',
               '2000-07-15', '2000-07-16'],
              dtype='datetime64[ns]', freq='D')

## Frequencies and Offsets

In [85]:
pd.timedelta_range(0, periods=9, freq="4h30min")

TimedeltaIndex(['0 days 00:00:00', '0 days 04:30:00', '0 days 09:00:00',
                '0 days 13:30:00', '0 days 18:00:00', '0 days 22:30:00',
                '1 days 03:00:00', '1 days 07:30:00', '1 days 12:00:00'],
               dtype='timedelta64[ns]', freq='270min')

# High-Performance Pandas: eval() and query()

## Motivating query() and eval(): Compound Expressions

In [96]:
import numpy as np
r = np.random.RandomState(99)
x = r.rand(1000)
y = r.rand(1000)
mask = (x > 0.5) & (y < .5)

In [95]:
import numexpr
mask_numexpr = numexpr.evaluate('(x > 0.5) & (y < 0.5)')
np.allclose(mask, mask_numexpr)

True

## pandas.eval() for Efficient Operations

In [99]:
import pandas as pd
nrows, ncols = 100, 10
rng = np.random.RandomState(99)
X1, X2, X3, X4 = (pd.DataFrame(rng.rand(nrows, ncols))
                      for i in range(4))

In [100]:
np.allclose(X1 + X2 + X3 + X4,
            pd.eval('X1 + X2 + X3 + X4'))

True

### Operations supported by pd.eval()

In [101]:
X1, X2, X3, X4, X5 = (pd.DataFrame(rng.randint(0, 100, (10, 3)))
                           for i in range(5))

#### Arithmetic operators

In [104]:
R1 = -X1 * X2 / (X3 - X4) + X5
R2 = pd.eval('-X1 * X2 / (X3 - X4) + X5')
np.allclose(R1, R2)

True

#### Comparison operators

In [105]:
R1 = (X1 < X2) & (X2 <= X3) & (X3 != X4)
R2 = pd.eval('X1 < X2 <= X3 != X4')
np.allclose(R1, R2)

True

#### Bitwise operators

In [109]:
R1 = (X1 < 0.5) & (X2 < 0.5) | (X3 < X4)
R2 = pd.eval('(X1 < 0.5) & (X2 < 0.5) | (X3 < X4)')
np.allclose(R1, R2)

True

#### Object attributes and indices

In [110]:
R1 = X2.T[0] + X3.iloc[1]
R2 = pd.eval('X2.T[0] + X3.iloc[1]')
np.allclose(R1, R2)

True

## DataFrame.eval() for Column-Wise Operations

In [111]:
df = pd.DataFrame(r.rand(100, 4), columns=['A', 'B', 'C', 'D'])
df.head()

A         B         C         D
0  0.166961  0.425648  0.681295  0.907439
1  0.453074  0.168990  0.674441  0.636627
2  0.593493  0.742968  0.511173  0.895446
3  0.760015  0.280609  0.494171  0.218167
4  0.940075  0.709629  0.445178  0.046797

In [114]:
R1 = (df['A'] - df['B']) / (df['C'] + 1)
R2 = pd.eval("(df.A - df.B) / (df.C + 1)")
np.allclose(R1, R2)

True

In [115]:
R3 = df.eval('(A - B) / (C + 1)')
np.allclose(R1, R3)

True

### Assignment in DataFrame.eval()

In [126]:
print('Original:\n',df.head())
df.eval('D = (A + B) / C', inplace=True)
print('\nAltered D:\n',df.head())
df.eval('C = (A - B) / C', inplace=True)
print('\nAltered C:\n',df.head())

Original:
           A         B         C         D
0  0.166961  0.425648  0.681295 -1.560732
1  0.453074  0.168990  0.674441  1.476837
2  0.593493  0.742968  0.511173 -4.570426
3  0.760015  0.280609  0.494171  1.072673
4  0.940075  0.709629  0.445178  3.186911

Altered D:
           A         B         C         D
0  0.166961  0.425648  0.681295  0.869826
1  0.453074  0.168990  0.674441  0.922339
2  0.593493  0.742968  0.511173  2.614496
3  0.760015  0.280609  0.494171  2.105799
4  0.940075  0.709629  0.445178  3.705720

Altered C:
           A         B         C         D
0  0.166961  0.425648 -0.379699  0.869826
1  0.453074  0.168990  0.421213  0.922339
2  0.593493  0.742968 -0.292415  2.614496
3  0.760015  0.280609  0.970122  2.105799
4  0.940075  0.709629  0.517650  3.705720


### Local variables in DataFrame.eval()

In [134]:
row_mean = df.mean(1)
R1 = df['A'] + row_mean
R2 = df.eval('A - @row_mean')
np.allclose(R1, R2)

False

## DataFrame.query() method

In [139]:
R1 = df[(df.A < 0.5) & (df.B < 0.5)]
R2= pd.eval('df[(df.A < 0.5) & (df.B < 0.5)]')
np.allclose(R1, R2)

True

In [138]:
R2 = df.query('A < 0.5 and B < 0.5')
np.allclose(R1, R2)

True