# Intro to NumPy

In [149]:
import numpy as np
np.__version__

'1.26.4'

## Understanding Data types in Python

### Python integer is more than an integer

In [23]:
L = list(range(20))
print("range is:", L)
print("L is a:",type(L[1]))

L = [str(i) for i in L]
print("range is:", L)
print("L is a:",type(L[1]))

L = [False, 3.0, 7, 'Taco', None]
print('The types for each element are:',[type(i) for i in L])


range is: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
L is a: <class 'int'>
range is: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
L is a: <class 'str'>
The types for each element are: [<class 'bool'>, <class 'float'>, <class 'int'>, <class 'str'>, <class 'NoneType'>]


### Fixed Arrays in Python

In [34]:
import array
L = list(range(10))
print(L)
A = array.array('I', L)
print(A)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
array('I', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [56]:
import numpy as np
#print('The array is:',np.array([3.14, 4, 7.0, 3]))
np.array([3.14, 4, 7.0, 3], dtype='float32')
#print('The float array is:',np.array([1, 2, 3, 4], dtype='float32'))

array([3.14, 4.  , 7.  , 3.  ], dtype=float32)

In [59]:
np.array([range(i, i + 5) for i in [1, 3, 5]])

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [5, 6, 7, 8, 9]])

### Creating Arrays

In [89]:
print('Array of float zeros:\n',np.zeros((2, 2),dtype=float))

print('\nArray filled with tacos:\n',np.full((3, 3), 'tacos'))

print('\nRange of 90 by 10 in an array:',np.arange(0, 100, 10))

print('\nFive numbers evenly between 0 and 2:',np.linspace(0, 2, 5))

print('\nIdentity matrix:\n',np.eye(4))

Array of float zeros:
 [[0. 0.]
 [0. 0.]]

Array filled with tacos:
 [['tacos' 'tacos' 'tacos']
 ['tacos' 'tacos' 'tacos']
 ['tacos' 'tacos' 'tacos']]

Range of 90 by 10 in an array: [ 0 10 20 30 40 50 60 70 80 90]

Five numbers evenly between 0 and 2: [0.  0.5 1.  1.5 2. ]

Identity matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [100]:
print('Randomized array:\n',np.random.random((2, 2)))

print('\nRandom numbers with a mean of 2:\n',np.random.normal(2, 1, (3, 3)))

print('\nRandom ints from 0 to 100:\n',np.random.randint(0, 100, (3, 3)))

print('\nUninitialized values:',np.empty(4),)

Randomized array:
 [[0.68815199 0.38433436]
 [0.31266998 0.89833294]]

Random numbers with a mean of 2:
 [[1.24881204 3.10866677 1.76029859]
 [2.19973783 3.81281752 1.84241323]
 [2.98825865 2.1636643  1.54590469]]

Random ints from 0 to 100:
 [[17 42 49]
 [18 65 90]
 [99  6 82]]

Uninitialized values: [0.68815199 0.38433436 0.31266998 0.89833294]


### Numpy Standard Data Types

In [148]:
print('Boolean Data type:',np.zeros(3, dtype='bool_'))

print('Integer Data type:',np.arange((10), dtype='intc'))

print('Float Data type:\n',np.eye((4), dtype='float_'))

print('Complex Data type:',np.ones(3, dtype='complex_'))

Boolean Data type: [False False False]
Integer Data type: [0 1 2 3 4 5 6 7 8 9]
Float Data type:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Complex Data type: [1.+0.j 1.+0.j 1.+0.j]


## Basics to NumPy Arrays

### NumPy Array Attributes

In [86]:
import numpy as np

L = np.random.randint(10, size=3)  # One-dimensional array
M = np.random.randint(10, size=(4, 4))  # Two-dimensional array
N = np.random.randint(10, size=(2, 7, 6))  # Three-dimensional array

print("N dimension:", N.ndim)
print("N shape:", N.shape)
print("N size:", N.size)

print("\ndtype:", N.dtype)
print("itemsize:", N.itemsize, "bytes")
print("nbytes:", N.nbytes, "bytes")

print('\n2D array:\n',M)
print('\nSpecific line of array:\n',M[3])
print('\nSpecific value of array:',M[3,2])


M[3, 0]=2.72 #Value will be truncated
print('\nInsertion of value into array',M[3])

N dimension: 3
N shape: (2, 7, 6)
N size: 84

dtype: int32
itemsize: 4 bytes
nbytes: 336 bytes

2D array:
 [[2 4 7 6]
 [8 8 1 6]
 [7 7 8 1]
 [5 9 8 9]]

Specific line of array:
 [5 9 8 9]

Specific value of array: 8

Insertion of value into array [2 9 8 9]


### One Dimensional Array Slicing

In [80]:
Z = np.arange(0,20,2)

print('Whole array:', Z)
print('First half:', Z[:5])
print('Second half:', Z[5:])
print('Middle section:', Z[3:7])
print('Every other starting at 2:', Z[8::-2])

Whole array: [ 0  2  4  6  8 10 12 14 16 18]
First half: [0 2 4 6 8]
Second half: [10 12 14 16 18]
Middle section: [ 6  8 10 12]
Every other starting at 2: [16 12  8  4  0]


### Two Dimensional Array Slicing

In [81]:
print('2D array:\n',M)
print('\nThe last three rows and columns:\n',M[2:, 1:])
print('\nInverted 2D array:\n',M[::-1, ::-1])

2D array:
 [[4 2 6 8]
 [2 2 7 2]
 [3 2 6 1]
 [2 3 6 7]]

The last three rows and columns:
 [[2 6 1]
 [3 6 7]]

Inverted 2D array:
 [[7 6 3 2]
 [1 6 2 3]
 [2 7 2 2]
 [8 6 2 4]]


In [22]:
print('2D array:\n',M)
M_sub = M[1:3, 1:3]
print('Middle of 2D array:\n',M_sub)

M_sub[0, 0] = 69
print('Altered 2D array:\n',M_sub)

M_sub_copy = M[0:, 0:].copy()
print('Copy of 2D array:\n',M_sub_copy)

M_sub_copy[0, 0] = 49
print('Altered copy of 2D array:\n',M_sub_copy)

print('Orignal 2D array:\n',M)


2D array:
 [[8 9 8 2]
 [4 5 4 1]
 [7 3 7 1]
 [2 0 6 4]]
Middle of 2D array:
 [[5 4]
 [3 7]]
Altered 2D array:
 [[69  4]
 [ 3  7]]
Copy of 2D array:
 [[ 8  9  8  2]
 [ 4 69  4  1]
 [ 7  3  7  1]
 [ 2  0  6  4]]
Altered copy of 2D array:
 [[49  9  8  2]
 [ 4 69  4  1]
 [ 7  3  7  1]
 [ 2  0  6  4]]
Orignal 2D array:
 [[ 8  9  8  2]
 [ 4 69  4  1]
 [ 7  3  7  1]
 [ 2  0  6  4]]


### Reshaping of arrays

In [82]:
a = np.arange(1, 17).reshape((4, 4))
print('Here is the 4x4 grid of the range of 1 to 16:\n',a)

a2 = np.array([7, 6, 3, 8])
print('Reshaped 1x4 array to 2x2:\n',a2.reshape((2,2)))

print('Reshaped 1x4 array to 4x1:\n',a2[:, np.newaxis])

Here is the 4x4 grid of the range of 1 to 16:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Reshaped 1x4 array to 2x2:
 [[7 6]
 [3 8]]
Reshaped 1x4 array to 4x1:
 [[7]
 [6]
 [3]
 [8]]


### Concatenation of arrays

In [83]:
x = np.array([7, 3, 6])
y = np.array([9, 5, 2])
print('The combined array is:',np.concatenate([x, y]))

z = [7, 7, 7]
print('\nThe 3D array is:',np.concatenate([x, y, z]))

Q = np.array([[6, 3, 8],
              [9, 5, 2]])
print('\nThe horizontal stacked array is:\n',np.concatenate([Q, Q],axis = 1))
print('\nThe horizontal stacked array is:\n',np.vstack([Q, Q]))


The combined array is: [7 3 6 9 5 2]

The 3D array is: [7 3 6 9 5 2 7 7 7]

The horizontal stacked array is:
 [[6 3 8 6 3 8]
 [9 5 2 9 5 2]]

The horizontal stacked array is:
 [[6 3 8]
 [9 5 2]
 [6 3 8]
 [9 5 2]]


### Splitting of arrays

In [84]:
x = [7, 2, 6, 49, 43, 8, 1, 5]
x1, x2, x3 = np.split(x, [2, 6])
print('The split up array in three sections:',x1, x2, x3)

grid = np.arange(16).reshape((4,4))
left, right = np.hsplit(grid, [2])
print('\nLeft side of the 4x4 array:\n',left)
print('\nRight side of the 4x4 array:\n',right)

The split up array in three sections: [7 2] [ 6 49 43  8] [1 5]

Left side of the 4x4 array:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Right side of the 4x4 array:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Univeral Functions

### The slowness of loops

In [90]:
import numpy as np

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
        
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

#big_array = np.random.randint(1, 100, size=1000000)
#%timeit compute_reciprocals(big_array)

array([0.14285714, 0.125     , 0.5       , 0.33333333, 0.33333333])

In [88]:
print(compute_reciprocals(values))
print(1.0 / values)

%timeit (1.0 / big_array)

[0.33333333 0.125      0.33333333 0.33333333 0.25      ]
[0.33333333 0.125      0.33333333 0.33333333 0.25      ]
2.37 ms ± 34.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [130]:
x = np.arange(9).reshape((3, 3))

print("The base array is:\n", x)
print("Each cell is increased by 3:\n", x + 3)
print("Each cell is decreased by 3:\n", np.subtract(x, 3))
print("Each cell is multiplied by 2:\n", x * 2)
print("Each cell is divided by 2:\n", np.divide(x, 2))
print("Each cell is floor divided by 2:\n", x // 2)

The base array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Each cell is increased by 3:
 [[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Each cell is decreased by 3:
 [[-3 -2 -1]
 [ 0  1  2]
 [ 3  4  5]]
Each cell is multiplied by 2:
 [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]
Each cell is divided by 2:
 [[0.  0.5 1. ]
 [1.5 2.  2.5]
 [3.  3.5 4. ]]
Each cell is floor divided by 2:
 [[0 0 1]
 [1 2 2]
 [3 3 4]]


In [132]:
x = np.arange(9).reshape((3, 3))

print("The inverse of the array is:\n", np.negative(x))
print("Each cell is raised to the power of 2:\n", x ** 2)
print("The remainder of the array is 2:\n", np.mod(x, 2))

print("The combination of array arithmetic:\n", -(2*x + 3) ** 2)


The inverse of the array is:
 [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]
Each cell is raised to the power of 2:
 [[ 0  1  4]
 [ 9 16 25]
 [36 49 64]]
The remainder of the array is 2:
 [[0 1 0]
 [1 0 1]
 [0 1 0]]
The combination of array arithmetic:
 [[  -9  -25  -49]
 [ -81 -121 -169]
 [-225 -289 -361]]


### Absolute value

In [147]:
x = np.arange(9).reshape((3, 3))
x2 = np.negative(x)
print('The inverse array is:\n',x2)
print('The absolute value of the array is:\n', np.absolute(x2))

x3 = np.array([3 + 4j, 12 - 5j, 6 + 0j, 0 + 7j])
print('The absolute value of the array is:\n', np.abs(x3))

The inverse array is:
 [[ 0 -1 -2]
 [-3 -4 -5]
 [-6 -7 -8]]
The absolute value of the array is:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
The absolute value of the array is:
 [ 5. 13.  6.  7.]


### Trigonometric functions

In [159]:
theta = np.linspace(0, np.pi*2, 4)

print("theta      = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         2.0943951  4.1887902  6.28318531]
sin(theta) =  [ 0.00000000e+00  8.66025404e-01 -8.66025404e-01 -2.44929360e-16]
cos(theta) =  [ 1.  -0.5 -0.5  1. ]
tan(theta) =  [ 0.00000000e+00 -1.73205081e+00  1.73205081e+00 -2.44929360e-16]


In [169]:
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [194]:
x = [2, 4, 6]

print("e to the power of x:", np.exp(x))
print("x squared:", np.power(x, 2))
print("x cubed:", np.power(x, 3))

y = [1,3,5,7]
print("\nln(x)    :", np.log(y))
print("log2(x)  :", np.log2(y))
print("log10(x) :", np.log10(y))

z = [0, .005, .05, .5]
print("\nexp(x) - 1:", np.expm1(z))
print("log(1 + x):", np.log1p(z))

e to the power of x: [  7.3890561   54.59815003 403.42879349]
x squared: [ 4 16 36]
x cubed: [  8  64 216]

ln(x)    : [0.         1.09861229 1.60943791 1.94591015]
log2(x)  : [0.         1.5849625  2.32192809 2.80735492]
log10(x) : [0.         0.47712125 0.69897    0.84509804]

exp(x) - 1: [0.         0.00501252 0.0512711  0.64872127]
log(1 + x): [0.         0.00498754 0.04879016 0.40546511]


### Specialized unfuncs

In [203]:
from scipy import special

x = [2, 4, 8]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x, 3)   =", special.beta(x, 3))

y = np.array([0, 0.25, 0.5, .75, 1.0])
print("erf(y)  =", special.erf(y))
print("erfc(y) =", special.erfc(y))
print("erfinv(y) =", special.erfinv(y))

gamma(x)     = [1.00e+00 6.00e+00 5.04e+03]
ln|gamma(x)| = [0.         1.79175947 8.52516136]
beta(x, 3)   = [0.08333333 0.01666667 0.00277778]
erf(y)  = [0.         0.27632639 0.52049988 0.71115563 0.84270079]
erfc(y) = [1.         0.72367361 0.47950012 0.28884437 0.15729921]
erfinv(y) = [0.         0.22531206 0.47693628 0.81341985        inf]


## Advanced Ufunc features

### Specifying output

In [213]:
x = np.arange(10)
y = np.empty(10)
np.multiply(x, 10, out=y)
print('Here is the multiples of 10 from 1 to 9:\n',y)

Here is the multiples of 10 from 1 to 9:
 [ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]


### Aggregates

In [238]:
x = np.arange(2, 7)
print(np.add.reduce(x))
print(np.add.accumulate(x))

print(np.multiply.reduce(x))
print(np.multiply.accumulate(x))

np.multiply.outer(x, x)

20
[ 2  5  9 14 20]
720
[  2   6  24 120 720]


array([[ 4,  6,  8, 10, 12],
       [ 6,  9, 12, 15, 18],
       [ 8, 12, 16, 20, 24],
       [10, 15, 20, 25, 30],
       [12, 18, 24, 30, 36]])

# Min, Max and Everything in Between

### Summing the values in an array

In [286]:
import numpy as np
L = np.random.random(10)
print('The sum of 10 numbers:',np.sum(L))

The sum of 10 numbers: 5.5112627811158275


### Minimum and Maximum

In [295]:
big_array = np.random.rand(1000)
print('Minimum of random numbers:',big_array.min())
print('Maximum of random numbers:',big_array.max())
print('Sum of random numbers:',big_array.sum())

Minimum of random numbers: 0.0019277898256591097
Maximum of random numbers: 0.9997375374315752
Sum of random numbers: 498.8851506922663


### Multi Dimensional aggregates

In [349]:
M = np.random.random((3, 4))
print('Sum of random array:',M.sum())
print('Minimum of first row of array:',M.min(axis=0))
print('Maximum of first column of array:',M.max(axis=1))
print('Mean of random array:',M.mean())
print('Product of random array:',M.prod())

Sum of random array: 6.63277133127297
Minimum of first row of array: [0.58013941 0.53337749 0.05755804 0.27638218]
Maximum of first column of array: [0.83075601 0.89630554 0.58013941]
Mean of random array: 0.5527309442727475
Product of random array: 6.926844769585629e-05


# Broadcasting

### Introducing Broadcasting

In [2]:
import numpy as np
a = np.array([2, 4, 6])
b = np.array([3, 3, 3])
print('Combination of similar arrays:',a + b)

c = np.ones((3,3))

print('\nCombination of different arrays:\n',a + c)

ModuleNotFoundError: No module named 'numpy'

In [369]:
a = np.arange(4)
b = np.arange(4)[:, np.newaxis]

print('The broadcasted arrays make:\n',a + b)

The broadcasted arrays make:
 [[0 1 2 3]
 [1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [383]:
M = np.ones((4, 4))
a = np.arange(4)
M + a[:, np.newaxis]
print('The product of the broadcast is:\n',np.logaddexp(M, a[:, np.newaxis]))

The product of the broadcast is:
 [[1.31326169 1.31326169 1.31326169 1.31326169]
 [1.69314718 1.69314718 1.69314718 1.69314718]
 [2.31326169 2.31326169 2.31326169 2.31326169]
 [3.12692801 3.12692801 3.12692801 3.12692801]]


### Centering an array

In [395]:
i = np.random.random((7,4))
imean = i.mean(0)
print(imean)
i_centered = i -imean
print(i_centered.mean(0))

[0.29570445 0.52741205 0.5937208  0.36973418]
[-1.58603289e-17  4.75809868e-17  1.58603289e-17 -6.34413157e-17]


# Comparisons, Masks and Boolean Logic

### Comparison Operators as ufuncs

In [6]:
x = np.array([0, 2, 4, 6, 8])
print('Cells results for less than:\n',x < 4)
print('\nCells results for greater than:\n',x > 4)
print('\nCells results for less than or equal to:\n',x <= 4)
print('\nCells results for greater than or equal to:\n',x >= 4)
print('\nCells results for does not equal 4:\n',x != 4)
print('\nCells results for equals 4:\n',x == 4)

Cells results for less than:
 [ True  True False False False]

Cells results for greater than:
 [False False False  True  True]

Cells results for less than or equal to:
 [ True  True  True False False]

Cells results for greater than or equal to:
 [False False  True  True  True]

Cells results for does not equal 4:
 [ True  True False  True  True]

Cells results for equals 4:
 [False False  True False False]


In [7]:
array = np.random.RandomState(5)
x = array.randint(10, size=(4, 4))
print('The boolean of results for each cell:\n',x <= 5)
print('Number of values less than or equal to 5:\n',np.count_nonzero(x <= 5))
print('Values in each row less than 5:\n',np.sum(x < 5,axis = 1))
print('Any values greater than 8?\n',np.any(x > 8))
print('All values greater than 2?\n',np.all(x > 2))

The boolean of results for each cell:
 [[ True False False  True]
 [False False  True False]
 [ True  True False  True]
 [ True False  True  True]]
Number of values less than or equal to 5:
 9
Values in each row less than 5:
 [2 1 3 2]
Any values greater than 8?
 True
All values greater than 2?
 False


In [8]:
bool(42), bool(0)
bool(42 and 0)
bool(42 or 0)

A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
A | B

x = np.arange(10)
(x > 4) & (x < 8)

array([False, False, False, False, False,  True,  True,  True, False,
       False])

# Fancy Indexing

### Exploring Fancy Idexing

In [29]:
import numpy as np
rand = np.random.RandomState(99)

x = rand.randint(100, size=10)
print('The whole random array:',x)

print('The specific numbers at index 8, 2 and 4:',[x[8], x[2], x[4]])

The whole random array: [ 1 35 57 40 73 82 68 69 52  1]
The specific numbers at index 8, 2 and 4: [52, 57, 73]


In [38]:
index = [5, 3, 9]
print('The specific numbers at index 5, 3 and 9:',x[index])

The specific numbers at index 3, 7 and 4: [82 40  1]


In [40]:
index = np.array([[5, 3],
                  [9, 6]])
print('The specific numbers at index 5, 3, 9 and 6:\n',x[index])

The specific numbers at index 5, 3, 9 and 6:
 [[82 40]
 [ 1 68]]


In [51]:
x = array.randint(10, size=(4, 4))
print('The 4x4 array is:\n',x)
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print('\nThe specified locations of cells in the array:',x[row, col])

The 4x4 array is:
 [[2 6 6 2]
 [7 0 3 7]
 [5 1 6 7]
 [3 9 7 9]]

The specified locations of cells in the array: [6 0 7]


### Combined Indexing

In [58]:
print('The 4x4 array is:\n',x)
print('\nThe cells in the third row of the array in a certain order:',x[2, [2, 0, 1]])
print('\nThe cells in the third row of the array in a certain order:\n',x[1:, [2, 0, 1]])

The 4x4 array is:
 [[2 6 6 2]
 [7 0 3 7]
 [5 1 6 7]
 [3 9 7 9]]

The cells in the third row of the array in a certain order: [6 5 1]

The cells in the third row of the array in a certain order:
 [[3 7 0]
 [6 5 1]
 [7 3 9]]


In [77]:
x = np.arange(10)
i = np.array([1, 4, 9, 6])
x[i] = 69
print('The first modified change is:',x)
x[i] -= 20
print('The second modified change is:',x)

The first modified change is: [ 0 69  2  3 69  5 69  7  8 69]
The second modified change is: [ 0 49  2  3 49  5 49  7  8 49]


In [97]:
x = np.zeros(10)
x[[0, 2]] = [3, 7]
print('The base array ready to be modified:',x)

i = [2, 7, 4, 9, 1, 3]
x[i] += 1   #One way to write an incremental index
print('The modified array with one indexed at the above locations:',x)

np.add.at(x, i, 2)  #Another way to write the incremental index
print('The modified array with one indexed at the above locations:',x)

The base array ready to be modified: [3. 0. 7. 0. 0. 0. 0. 0. 0. 0.]
The modified array with one indexed at the above locations: [3. 1. 8. 1. 1. 0. 0. 1. 0. 1.]
The modified array with one indexed at the above locations: [ 3.  3. 10.  3.  3.  0.  0.  3.  0.  3.]


# Sorting arrays